### ISSUE TITLE
Decrypt selection fails silently

### ISSUE THREAD

**Issue by dpsenner** [jvalecillos/vscode-gpg#13]
## Steps to reproduce:

1. Select text in a file
1. CTRL+SHIFT+P
1. GPG: Encrypt
1. Select me as recipient
1. Enter
1. Select encrypted text
1. CTL+SHIFT+P
1. GPG: Decrypt
1. Enter passphrase
1. Enter

## Expectations:

The selected encrypted text should be replaced by the decrypted plaintext.

## What happens instead:

The selected encrypted text stays where it is.

**Comment by jvalecillos** [comment]
Hello @dpsenner, thanks for reporting. Could you check the [lastest version](https://github.com/jvalecillos/vscode-gpg/releases/tag/1.1.2) of the extension. I have added the error messages that come from the `gpg` cli, having that information it will be easier to identify the issue.

**Comment by dpsenner** [comment]
While I appreciate your efforts and am thankful for all the good OSS brings to the world, I do not have the time to further debug the situation. Sorry. I am using the GnuPG-Tool extension and it does satisfy my needs.

**Comment by jvalecillos** [comment]
Closed for inactivity. No more info is provided to reproduce the issue.

**Comment by dpsenner** [comment]
@jvalecillos I just had a minute and gave this a try. When I attempt to decrypt a selection using GPG v1.1.0, it fails with:

![image](https://github.com/jvalecillos/vscode-gpg/assets/8520682/9ef9f8f3-251f-4ea1-851b-3d075fb42a7d)
