### ISSUE TITLE
Is gpg nessary to send commits?

### ISSUE THREAD

**Issue by BeardedDaddy** [jvalecillos/vscode-gpg#15]
Type: <b>Performance Issue</b>

Good afternoon, I wanted it know is it necessary to have gpg in vs code to send commits? I want to remove it because I can send my commits to GitHub because I can't remember my passphrase.

Extension version: 0.1.2
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.93GB free)|
|Process Argv|--crash-reporter-id 260634ff-654b-4f69-8e91-d3a070cbac8d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    85	 10244	code main
    0	    39	  6492	   utility-network-service
    0	   146	 13984	   window (Learning Python - Visual Studio Code)
    0	    84	 15496	   issue-reporter
    0	   108	 17416	   shared-process
    0	    61	 18704	     ptyHost
    0	    72	 20080	     fileWatcher
    0	   112	 18620	   gpu-process
    0	   221	 19892	   extensionHost
    0	   102	  2948	     "C:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\grevy\.vscode\extensions\googlecloudtools.cloudcode-1.20.2\dist\server\server.js --node-ipc --clientProcessId=19892
    0	    70	  5712	     "C:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19892
    0	    69	 11104	     "C:\Users\grevy\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\grevy\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=19892
    0	    26	 19952	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Learning Python - Visual Studio Code)
|    Folder (Learning Python): 6321 files
|      File types: py(1797) pyc(1552) pyi(1076) dll(149) svg(122) json(113)
|                  js(63) exe(59) txt(36) md(33)
|      Conf files: package.json(10) settings.json(6) launch.json(3)
|                  tslint.json(2) dockerfile(2) devcontainer.json(1) sln(1)
|      Launch Configs: python;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
vsccc:30566497
fc301958:30567733

```

</details>

**Comment by mariogarridopt** [comment]
GPG Git and vscode-gpg are different things. This is an extension that allows you to encrypt files/messages.

GPG can connect with git to sign your commits, this is a feature of git.

Installing vscode-gpg will not enable any git-gpg feature.

**Comment by BeardedDaddy** [comment]
Thank you. I appreciate the response.
