### ISSUE TITLE
Unable to decode/encode binary 

### ISSUE THREAD

**Issue by trev-dev** [jvalecillos/vscode-gpg#7]
I can't seem to decrypt original/binary gpg files. Armored ASCII works fine. Am I making a mistake somewhere?

**Comment by jvalecillos** [comment]
The extension currently only works Armored ASCII files because it relies on the GPG program to perform the decoding.
It would be possible to decrypt a binary file with a separate option as long as vscode is able to open the file in first place.

**Comment by trev-dev** [comment]
Good to know! I'll do a little poking around. Emacs can open any gpg file be it armored or binary and just display it decrypted. To boot, when you write a change, it encrypts the buffer and over-writes the binary. If we were working with a buffer in memory vs a file on disk, we could achieve a similar effect.

**Comment by jvalecillos** [comment]
@trev-dev it is now possible to decrypt binary files with the extension `.gpg` and armored files with the extension `.asc`. The option appears as a context menu when clicking on the file in the sidebar. This feature is now available in the version [0.1.0](https://github.com/jvalecillos/vscode-gpg/releases/tag/0.1.0).

The missing feature would be encrypting the file as binary, the catch is that is not possible to show it in the editor.

Please let me know if the new version works for you and if you have any question.

**Comment by trev-dev** [comment]
@jvalecillos I just absent mindently opened an encrypted binary this week and it worked! I remembered this issue some time later and can see there's a reason for that :)

Thank you.
