### ISSUE TITLE
Encrypt/decrypt files

### ISSUE THREAD

**Issue by rhysjtevans** [jvalecillos/vscode-gpg#8]
It would be great to be able to right-click a file in the workspace explorer window and have the option to encrypt/decrypt and it would encrypt with the same file but appending some file extension

**Comment by jvalecillos** [comment]
This feature is now available in the version [0.1.0](https://github.com/jvalecillos/vscode-gpg/releases/tag/0.1.0)

**Comment by jvalecillos** [comment]
This feature is now available in the version [0.1.0](https://github.com/jvalecillos/vscode-gpg/releases/tag/0.1.0)
